### ISSUE TITLE
AttributeError: 'list' object has no attribute 'update'

### ISSUE THREAD

**Issue by mingyuezhaowo** [shijl0925/python-gerrit-api#14]
Hello, 
I got a error when query:
code :
change = gerrit.changes.get('?q=owner:self+status:open')

error log:
Traceback (most recent call last):
  File "F:\Doc\Batch_review\gerrit_batch_review\python-gerrit-api-master\python_gerrit_api.py", line 5, in <module>
    change = gerrit.changes.get('?q=owner:self+status:open')
  File "F:\Doc\Batch_review\gerrit_batch_review\python-gerrit-api-master\gerrit\changes\changes.py", line 32, in get
    return GerritChange.parse(result, gerrit=self.gerrit)
  File "F:\Doc\Batch_review\gerrit_batch_review\python-gerrit-api-master\gerrit\utils\models.py", line 26, in parse
    data.update(kwargs)
AttributeError: 'list' object has no attribute 'update'

**Comment by shijl0925** [comment]
useful code:

change = gerrit.changes.search('q=owner:self+status:open')
